include: package:very_good_analysis/analysis_options.5.0.0.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false

analyzer:
  exclude:
    - "**/generated/**"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - lib/res.dart
    - lib/generated/*