/// Generated by AssetsRefGenerator on 2021/02/07
class Res {
  static const String facebook = "assets/icons/facebook.png";
  static const String github = "assets/icons/github.png";
  static const String instagram = "assets/icons/instagram.png";
  static const String linkedin = "assets/icons/linkedin.png";
  static const String mob_dev = "assets/icons/mob_dev.png";
  static const String pen = "assets/icons/pen.png";
  static const String twitter = "assets/icons/twitter.png";
  static const String web = "assets/icons/web.png";
  static const String comingsoon = "assets/images/comingsoon.jpg";
}
