name: Analyze code

# Trigger the Analyze code workflow
on:
  pull_request:
    branches: [ master ]

jobs:
  # Set up Flutter for all other tasks.
  setup:
    runs-on: ${{ matrix.os }}
    env:
      PUB_CACHE: ~/.pub-cache

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install pub Dependencies
        run: flutter pub get

      - name: Activate intl
        run: flutter pub global activate intl_utils

      - name: Generate localization files
        run: flutter pub global run intl_utils:generate

      - name: Check for any formatting issues in the code.
        run: dart format --set-exit-if-changed lib/

      - name: Statically analyze the Dart code for any errors.
        run: dart analyze lib/

      - name: Build web app
        run: flutter build web