name: Build and Deploy to Netlify

on:
  push:
    tags:
      - '*'

jobs:
  # Set up Flutter for all other tasks.
  setup:
    runs-on: ${{ matrix.os }}
    env:
      PUB_CACHE: ~/.pub-cache

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.19.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
        
      - name: Disbale analytics of flutter
        run: flutter config --no-analytics

      - name: Install pub Dependencies
        run: flutter pub get

      - name: Check for any formatting issues in the code.
        run: dart format --set-exit-if-changed lib/

      - name: Statically analyze the Dart code for any errors.
        run: dart analyze lib/

      - name: Statically analyze the Dart code for any errors.
        run: dart analyze lib/

      - name: Build web app
        run: flutter build web

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build/web'
          production-branch: master
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
